version: '3.8'

services:
  payment-db:
    image: mongo:6.0
    container_name: payment-db-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: payments_db
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  payment-service:
    build: .
    container_name: payment-service-app
    ports:
      - "8084:8084"
    depends_on:
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      MONGO_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@payment-db:27017/payments_db?authSource=admin
      KAFKA_URL: kafka:29092
      EXTERNAL_API_URL: ${EXTERNAL_API_URL}
      JWT_KEY: ${JWT_KEY}